apiVersion: apps/v1
kind: Deployment
metadata:
   name: barramentoDeEventos-deployment
spec:
   replicas: 1
   selector:
      matchLabels:
         app: barramentoDeEventos
   template:
      metadata:
         labels:
            app: barramentoDeEventos
      spec:
         containers:
            - name: barramentoDeEventos
              image: mss-tweezer-barramentoeventos
              imagePullPolicy: Never
              resources:
                 limits:
                    memory: 256Mi
                    cpu: 1

--- 

apiVersion: v1
kind: Service
metadata:
  name: barramentoDeEventos-clusterip-service
spec:
  selector:
    app: barramentoDeEventos
  ports:
  - name: barramentoDeEventos
    protocol: TCP
    port: 10000
    targetPort: 10000