apiVersion: apps/v1
kind: Deployment
metadata:
   name: posts-deployment
spec:
   replicas: 1
   selector:
      matchLabels:
         app: posts
   template:
      metadata:
         labels:
            app: posts
      spec:
         containers:
            - name: posts
              image: mss-tweezer-posts
              imagePullPolicy: Never
              resources:
                 limits:
                    memory: 256Mi
                    cpu: 1

--- 

apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-service
spec:
  selector:
    app: posts
  ports:
  - name: posts
    protocol: TCP
    port: 5002
    targetPort: 5002