apiVersion: apps/v1
kind: Deployment
metadata:
   name: usuarios-deployment
spec:
   replicas: 1
   selector:
      matchLabels:
         app: usuarios
   template:
      metadata:
         labels:
            app: usuarios
      spec:
         containers:
            - name: usuarios
              image: mss-tweezer-usuarios
              imagePullPolicy: Never
              resources:
                 limits:
                    memory: 256Mi
                    cpu: 1

--- 

apiVersion: v1
kind: Service
metadata:
  name: usuarios-clusterip-service
spec:
  selector:
    app: usuarios
  ports:
  - name: usuarios
    protocol: TCP
    port: 5001
    targetPort: 5001